name: Auto PR and Merge Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .Net 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Setup Node.JS 26
        uses: actions/setup-node@v4
        with:
          node-version: "26.x"

      - name: Create PR and Auto-Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head ${{ github.ref_name }} --title "Auto PR: ${{ github.ref_name }}" --body "CI/CD automation created by the developer." || true
          sleep 7
          gh pr merge ${{ github.ref_name }} --auto --squash
